FROM httpd:latest

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    dnsutils \
    && rm -rf /var/lib/apt/lists/*

# Configurar ServerName para evitar warning
RUN echo "ServerName localhost" >> /usr/local/apache2/conf/httpd.conf

# Configurar permisos
RUN chown -R www-data:www-data /usr/local/apache2/htdocs
RUN chmod -R 755 /usr/local/apache2/htdocs

# Exponer puerto
EXPOSE 80

# Comando por defecto
CMD ["httpd-foreground"]